# Generated by Django 5.0.3 on 2024-04-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_templatefield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="OCRLocation",
            new_name="template_path",
        ),
        migrations.RemoveField(
            model_name="template",
            name="image",
        ),
        migrations.CreateModel(
            name="OCRLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_locations",
                        to="app.template",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TemplateField",
        ),
    ]
