# Generated by Django 5.0.3 on 2024-04-03 11:57
from django.db import migrations

from app.models import Template, OCRLocation

def initialize_data(apps, schema_editor):
    # Create Template instances
    template1 = Template.objects.create(name='Attestation RIB', template_path='../static/templates/template1.jpeg')
    template2 = Template.objects.create(name='Fiche Exemple', template_path='../static/templates/template2.png')

    # Define OCR locations data
    OCR_LOCATIONS_1 = [
        {"name": "Name", "bbox": (180, 676, 378 - 180, 694 - 676)},
        {"name": "Agence", "bbox": (504, 656, 619 - 504, 672 - 656)},
        {"name": "Date", "bbox": (327, 654, 409 - 327, 670 - 654)},
        {"name": "RIB", "bbox": (181, 573, 750 - 181, 600 - 573)}
    ]

    OCR_LOCATIONS_2 = [
        {"name": "Nom", "bbox": (413, 342, 1190 - 413, 422 - 342)},
        {"name": "Prenom", "bbox": (413, 432, 1190 - 413, 512 - 432)},
        {"name": "Adresse", "bbox": (291, 510, 1200 - 291, 610 - 510)},
        {"name": "NUM", "bbox": (315, 635, 1200 - 315, 721 - 635)}
    ]

    # Create OCRLocation instances for template1
    for loc_data in OCR_LOCATIONS_1:
        OCRLocation.objects.create(template=template1, name=loc_data["name"], x=loc_data["bbox"][0], 
                                    y=loc_data["bbox"][1], width=loc_data["bbox"][2], height=loc_data["bbox"][3])

    # Create OCRLocation instances for template2
    for loc_data in OCR_LOCATIONS_2:
        OCRLocation.objects.create(template=template2, name=loc_data["name"], x=loc_data["bbox"][0], 
                                    y=loc_data["bbox"][1], width=loc_data["bbox"][2], height=loc_data["bbox"][3])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_ocrlocation_template_template_path_and_more"),
    ]

    operations = [ migrations.RunPython(initialize_data),]
